server:
  port: 8082

inventory:
  service:
    url: http://inventory-service:8083/api/inventories

cache:
  refresh:
    interval: 300000 # 5 min

spring:
  application:
    name: Shop-Service
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: test1234
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
