server:
  port: 8081

base:
  uri: mongodb://mongodb_orders:27017

spring:
  application:
    name: Orders-Service

  data:
    mongodb:
      database: orders
      uri: ${base.uri}/${spring.data.mongodb.database}
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
