server:
  port: 8082

inventory:
  service:
    url: http://inventory-service:8083/api/inventories

spring:
  application:
    name: Network-Service
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: test1234
