server:
  port: ${SERVER_PORT:8083}

base:
  uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin}@mongodb_inventory:27017

spring:
  application:
    name: Inventory-Service

  data:
    mongodb:
      database: ${DATABASE:inventories}
      uri: ${base.uri}/${spring.data.mongodb.database}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
