server:
  port: 8071

spring:
  application:
    name: shop-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-service
              uri: http://inventory-service:8083
              predicates:
                - Path=/api/inventories/**

            - id: shop-service
              uri: http://shop-service:8082
              predicates:
              - Path=/api/shop/**

            - id: orders-service
              uri: http://orders-service:8081
              predicates:
              - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka